// SPDX-FileCopyrightText: GARDENA GmbH
//
// SPDX-License-Identifier: GPL-3.0-or-later

//! The full RPC API we implement using [tokio-task-rpc].

use crate::device::ValueDescriptionList as _;
use crate::storage;
use crate::Error;
use anyhow::anyhow;
use anyhow::Context as _;
use chrono::offset::Offset as _;
use chrono::Timelike;
use lwm2m::Endpoint;
use rand::Rng as _;

pub(super) const ONLINE_PING_INTERVAL: std::time::Duration = std::time::Duration::from_secs(9000);
const OFFLINE_PING_INTERVAL: std::time::Duration = std::time::Duration::from_secs(900);
pub(super) const MAX_UNINCLUDED_DURATION: std::time::Duration =
    std::time::Duration::from_secs(5 * 60);

/// Quickly accessible device data.
///
/// See [DeviceHandle] for details.
pub struct DeviceHandleData {
    pub bnw_id: String,
}

/// Attaches locked data to a generated device handle
///
/// - we can only access [Device](super::Device) data through [DeviceHandleInner]
/// - `lib.rs` does need to iterate the device handle list and obtain some data
///   for every device in certain cases
/// - [DeviceHandleInner] is generated and not extendable
///
/// Solution:
/// We just wrap the actual device-handle and add a data-field that is shared
/// with the device-task through a mutex.
/// That way we can put data which we want to access in a fast way without using
/// the RPC into [DeviceHandleData].
#[allow(rustdoc::private_intra_doc_links)]
#[derive(Clone)]
pub struct DeviceHandle {
    /// The handle generated by [tokio-task-rpc].
    inner: DeviceHandleInner,
    /// The additional data.
    data: std::sync::Arc<std::sync::Mutex<DeviceHandleData>>,
}

impl core::ops::Deref for DeviceHandle {
    type Target = DeviceHandleInner;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

impl core::ops::DerefMut for DeviceHandle {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.inner
    }
}

impl DeviceHandle {
    pub(super) fn new(data: DeviceHandleData) -> (Self, DeviceReceiver) {
        let data = std::sync::Arc::new(std::sync::Mutex::new(data));
        let (inner, receiver) = DeviceHandleInner::new();

        (Self { inner, data }, receiver)
    }

    /// Clone this handle without increasing reference-count.
    ///
    /// This is used to create handles for internal tasks so the one we give
    /// out to the user(and it's clones) is the only one that's counted.
    /// This means that the receiver task gets stopped when the user drops
    /// all their handles - which is exactly what we want.
    ///
    /// NOTE: it's currently private since there's no use case for API users to
    ///       create uncounted clones. Change it if one arises.
    pub(super) fn clone_uncounted(&self) -> Self {
        Self {
            inner: self.inner.clone_uncounted(),
            data: self.data.clone(),
        }
    }

    pub fn bnw_id(&self) -> String {
        self.data.lock().unwrap().bnw_id.clone()
    }
}

#[tokio_task_rpc::interface(
    handle_name = "DeviceHandleInner",
    enum_visibility = "pub(super)",
    // we allow Deref-ing to the inner handle
    handle_visibility = "pub",
    handlefns_visibility = "pub(super)",
    receiver_visibility = "pub(super)"
)]
impl crate::device::Device {
    /// Return LWM2M full representation.
    ///
    /// This includes all objects and all readable resources with all their
    /// instances.
    pub async fn as_ipso(&mut self) -> Result<Option<serde_json::Value>, Error> {
        if !self.description.included {
            return Ok(None);
        }
        Ok(Some(self.json_endpoint().await?))
    }

    /// Call this when the device sent us a status message.
    #[tokio_task_rpc(nowait)]
    #[tracing::instrument(name = "status-report", skip_all)]
    pub async fn handle_status(&mut self, status: lsdl::RawStatus) -> Result<(), Error> {
        tracing::info!(
            "Reported status type: {}, code: {}, level: {}, data: {:?}",
            status.type_id,
            status.code,
            status.level,
            status.data,
        );

        // device spamming value_reporting_queue_full?
        if status.type_id == 200 && status.code == 43 && self.description.is_cbt2() {
            tracing::debug!("Dropping status report VALUE_REPORTING_QUEUE_FULL");
            return Ok(());
        }

        self.persistent.status = Some(status);
        self.save_persistent_state()
            .await
            .context("can't save persistent state")?;

        self.publish_resource_instances(
            lwm2m::ObjectType::LemonbeatStatusMessage,
            0,
            &[
                (lwm2m::objects::LEMONBEAT_STATUS_MESSAGE_TYPE, 0),
                (lwm2m::objects::LEMONBEAT_STATUS_MESSAGE_CODE, 0),
                (lwm2m::objects::LEMONBEAT_STATUS_MESSAGE_LEVEL, 0),
                (lwm2m::objects::LEMONBEAT_STATUS_MESSAGE_DATA, 0),
            ],
        )
        .await?;
        Ok(())
    }

    /// Just received a device description without explicitly requesting it.
    ///
    /// This can happen in the following situations:
    /// - included=0: device is in inclusion mode (battery inserted, factory reset, fota update)
    /// - included=1: device rebooted, device button pressed
    ///
    /// In case that the device has just ran an update, it needs to be re-included.
    #[tokio_task_rpc(nowait)]
    pub async fn received_device_description(
        &mut self,
        description: Box<crate::storage::DeviceDescription>,
    ) -> Result<(), Error> {
        tracing::debug!("Description updated: {:#?}", description);

        let inclusion_status_changed = self.description.included != description.included;
        self.set_description(description).await;

        // we just received data, so the device is definitely online now
        self.set_online(true).await;

        self.dont_delete_until = tokio::time::Instant::now() + MAX_UNINCLUDED_DURATION;

        // this is a workaround with the goal to not block the RPC callee
        // during the whole inclusion process.
        // Usually you'd wait for this synchronously
        if matches!(
            self.persistent.firmware_update_state,
            lwm2m::FirmwareUpdateState::Updating
        ) {
            return self.fota_on_device_description().await;
        }

        if self.description.included {
            // The device was included without our knowledge. Possible reasons:
            // - A developer included it without lemonbeatd. Possibly even with
            //   another dongle that uses the same network key.
            // - a hacker included it somehow.
            if inclusion_status_changed {
                tracing::error!("Device included itself. Exclude and forget");

                self.forget("self-included device").await;
                return Ok(());
            }

            self.publish_device_object()
                .await
                .context("can't publish device-description report to IPC")?;
        } else {
            if inclusion_status_changed {
                tracing::info!("Device factory reset, removing device");

                self.forget("factory reset device").await;

                // You might think that the event below should be sent anyway.
                // I'd disagree because we wouldn't have any device struct so
                // effectively it isn't includable, yet.
                // NOTE: should we fix this by not calling `forget`?
                return Ok(());
            }

            tracing::info_span!("inclusion").in_scope(|| {
                tracing::info!("Device available for inclusion");
            });

            if let Err(e) = self
                .publish_includable_device(false, false, 0, lwm2m::Method::Update)
                .await
            {
                tracing::error!("Failed to publish includable device: {:?}", e);
            }
        }

        Ok(())
    }

    /// Update value from report.
    #[tokio_task_rpc(nowait)]
    #[tracing::instrument(name = "state", skip_all)]
    pub async fn update_values(&mut self, values: Vec<storage::Value>) -> Result<(), Error> {
        let mut updates_resources = Vec::new();

        for value in values {
            match self.update_value(value).await {
                Err(e) => tracing::warn!("Can't update value: {}", e),
                Ok(Some(v)) => updates_resources.push(v),
                // value wasn't updated
                Ok(None) => (),
            }
        }

        self.set_online(true).await;

        // AWS cost optimisation: filter unnecessary reports that only contain a rf_link_quality
        // value from being sent to the cloud.
        // Unfortunately, some devices (epp/mowers) respond with such a single value message
        // if rf_link_quality is requested by sending the corresponding "command" (ie. don't
        // include the command value as well). So also considering if recently a value was written
        // to the device and when last value got published.
        if updates_resources.len() == 1 {
            let (resource_id, _) = updates_resources[0];

            if let Ok(value_description) = self.value_descriptions.by_resource_id(resource_id) {
                if value_description.name.as_deref() == Some("rf_link_quality") {
                    let now = tokio::time::Instant::now();

                    let recent_write = if let Some(last_write) = self.last_write {
                        now.duration_since(last_write).as_secs() <= 15
                    } else {
                        false
                    };

                    let recent_publish =
                        if let Some(last_publish) = self.last_rf_link_quality_publish {
                            now.duration_since(last_publish).as_secs() <= 24 * 60 * 60
                        } else {
                            false
                        };

                    if !recent_write && recent_publish {
                        tracing::info!(
                            "Filtered value rf_link_quality, recent write {}, recent publish {}",
                            recent_write,
                            recent_publish,
                        );
                        return Ok(());
                    }
                }
            }
        }

        if !updates_resources.is_empty() {
            // extremely ugly hack: beginning of the season 23 we already loose events in the cloud
            // at the full hour as most schedules start at 5, 6, 7 or 8am. Will need to find a way
            // so that customers either choose more random start times or let them know that we
            // randomize the start times on our end. Until then a small delay in forwarding
            // events at the full hour could limit the peaks already by a factor of 2.
            //
            // Only devices with a well synched clock contribute to such spikes. So we can keep
            // the time window very small were events should get delayed. Also: delaying an event
            // here means that the device is not responsive for any other requests during that time.
            //
            // Lastly: not creating a config for these values as this mechanism is not supposed to
            // stay for long (remove after 2023 sesaon).
            let now = chrono::Utc::now();
            if (self.description.is_lawnmower() || self.description.is_watering_device())
                && now.minute() == 0
                && now.second() < 7
            {
                tracing::info!("Delaying mowing/watering reports at the full hour");
                let delay =
                    std::time::Duration::from_millis(rand::thread_rng().gen_range(0..10000));
                tokio::time::sleep(delay).await;
                tracing::info!("Releasing mowing/watering reports at the full hour");
            }

            // check if rf_link_quality will be published
            if let Ok(value_description) = self.value_descriptions.by_name("rf_link_quality") {
                if updates_resources
                    .iter()
                    .any(|(resource_id, _)| *resource_id == value_description.id as usize)
                {
                    self.last_rf_link_quality_publish = Some(tokio::time::Instant::now());
                }
            }

            self.publish_resource_instances(lwm2m::ObjectType::Lemonbeat, 0, &updates_resources)
                .await?;
        }

        Ok(())
    }

    /// Go through the full inclusion process for this device.
    ///
    /// This includes post-inclusion.
    #[tokio_task_rpc(nowait)]
    #[tracing::instrument(name = "inclusion", skip_all)]
    pub async fn include(&mut self) -> Result<(), Error> {
        // the radio module is allowed to be re-included because it looses it's
        // inclusion after each cold-boot.
        // In that case our storage says that the device is included even
        // though it's not.
        if self.description.included {
            tracing::warn!("Attempted inclusion on included device, ignore");
            return Ok(());
        }

        if let Err(e) = self
            .publish_includable_device(true, false, 0, lwm2m::Method::Update)
            .await
        {
            tracing::error!("Failed to publish in-progress includable device: {:?}", e);
        }

        let res = self.include_inner().await;

        let inclusion_error = res.as_ref().map_or_else(|_| 1, |_| 0);
        if let Err(e) = self
            .publish_includable_device(true, true, inclusion_error, lwm2m::Method::Update)
            .await
        {
            tracing::error!("Failed to publish completed includable device: {:?}", e);
        }

        // NOTE: There's no reason to delete the device if this failed
        //       because the caller can simply retry
        if res.is_ok() {
            tracing::info!(
                remote = true,
                metric_name = "inclusion",
                metric_value = true,
                "Inclusion succeeded"
            );

            if let Err(e) = self
                .publish_includable_device(true, true, inclusion_error, lwm2m::Method::Delete)
                .await
            {
                tracing::error!("Failed to publish deleted includable device: {:?}", e);
            }

            if let Err(e) = self
                .lwm2m_pub_service
                .remove_includable_device(self.description.address)
            {
                tracing::error!("Failed to remove includable device: {:?}", e);
            }

            if let Err(e) = self.publish_endpoint().await {
                tracing::error!("Failed to publish endpoint: {:?}", e);
            }
        } else {
            tracing::warn!(
                metric_name = "inclusion",
                metric_value = false,
                "Inclusion failed"
            );
        }

        res
    }

    /// Blocking version of [include](Self::include_sync).
    pub async fn include_sync(&mut self) -> Result<(), Error> {
        self.include().await
    }

    /// Process a IPC device request.
    ///
    /// On success, This will return the answer that should be send back to the
    /// sender.
    pub async fn handle_ipc_request(
        &mut self,
        request: lwm2m::Request,
    ) -> Result<serde_json::Value, Error> {
        if self.description.included {
            Ok(self.handle_request(request).await?)
        } else {
            Err(anyhow!("device is not included"))
        }
    }

    /// Internal function for triggering a ping (if needed).
    ///
    /// This must only be called by the internal ping task. Returns the
    /// duration to wait until the next ping.
    pub(super) async fn try_ping(&mut self) -> Result<std::time::Duration, Error> {
        if !self.description.included {
            tracing::trace!("Device is not included, don't ping");
            return Ok(std::time::Duration::MAX);
        }

        let now = tokio::time::Instant::now();

        if !self.online()
            && now
                .checked_duration_since(self.online_changed_at)
                .ok_or_else(|| anyhow!("time went backwards in 24h check calculation"))?
                >= std::time::Duration::from_secs(24 * 60 * 60)
        {
            tracing::info!("Device was offline for 24h, stop pinging");
            return Ok(std::time::Duration::MAX);
        }

        // If there never was any communication we ping immediately.
        // This can happen when the device was loaded from storage.
        if let Some(last_communication_attempt) = self.last_communication_attempt {
            let nextping = last_communication_attempt
                .checked_add(if self.online() {
                    ONLINE_PING_INTERVAL
                } else {
                    OFFLINE_PING_INTERVAL
                })
                .ok_or_else(|| anyhow!("next ping time doesn't fit into `Instant`"))?;
            if nextping > now {
                return nextping.checked_duration_since(now).ok_or_else(|| {
                    anyhow!("BUG: checked_duration_since failed during nextping calculation")
                });
            }
        }

        // we go back to sleep immediately because there's nothing to do after
        // the ping
        match self
            .request_config_status_raw(Some(crate::device::GOTO_SLEEP_IMMEDIATELY))
            .await
        {
            Ok(_) => {
                tracing::info!("Ping successful");
                Ok(ONLINE_PING_INTERVAL)
            }
            Err(e) => {
                tracing::info!("Ping failed");
                tracing::debug!("Ping failed due to: {:?}", e);
                Ok(OFFLINE_PING_INTERVAL)
            }
        }
    }

    /// Internal function for triggering an UTC offset change (if needed).
    ///
    /// This must only be called by the internal utc update task. Returns the
    /// duration to wait until the next check.
    #[tracing::instrument(name = "time-sync", skip_all)]
    pub(super) async fn try_set_utc_offset(&mut self) -> Result<std::time::Duration, Error> {
        if !self.description.included {
            tracing::trace!("Device is not included, don't set utc offset");
            return Ok(std::time::Duration::MAX);
        }

        if !self.online() {
            tracing::trace!("Device is not online, don't set utc offset");
            return Ok(std::time::Duration::MAX);
        }

        let offset = chrono::Local::now().offset().fix().local_minus_utc();
        if self.persistent.time_offset == Some(offset) {
            tracing::trace!("Device already has utc_offset={}, don't set", offset);
            return Ok(std::time::Duration::MAX);
        }

        tracing::info!("Set utc offset to {}", offset);

        // If we fail we have no idea what state the device is in.
        // Also, we might loose power during the process.
        self.persistent.time_offset = None;
        self.save_persistent_state()
            .await
            .context("can't save persistent state (pre)")?;

        self.set_calendar_timezone(offset, Some(crate::device::GOTO_SLEEP_DURATION))
            .await
            .context("can't set timezone")?;

        // Config mode used to be lsdl::ConfigurationMode::SaveAndReset before BNW. Likely
        // it does not make any difference because neither state machines nor calendars are used
        // any longer. Unfortunately, we did not document the decision that lead to SaveAndPreserve.
        self.set_config_mode(
            lsdl::ConfigurationMode::SaveAndPreserve,
            Some(crate::device::GOTO_SLEEP_DURATION),
        )
        .await
        .context("can't set config mode")?;

        let config_status = self
            .request_config_status(Some(crate::device::GOTO_SLEEP_DURATION))
            .await?;
        if config_status != lsdl::CONFIGURATION_STATUS_IDLE {
            anyhow::bail!("config didn't finish. device will probably roll back");
        }

        // this is the last request, let's go back to sleep
        let offset_device = self
            .request_calendar_timezone(Some(crate::device::GOTO_SLEEP_IMMEDIATELY))
            .await
            .context("can't get calendar timezone")?;
        if offset_device != offset {
            anyhow::bail!(
                "device didn't apply our offset({}) and still has {}",
                offset,
                offset_device
            );
        }

        self.persistent.time_offset = Some(offset_device);
        tracing::info!("Successfully set utc-offset to {}", offset);

        self.save_persistent_state()
            .await
            .context("can't save persistent state (post)")?;

        self.publish_resource_instance(
            lwm2m::ObjectType::Device,
            0,
            lwm2m::objects::DEVICE_UTC_OFFSET,
            0,
        )
        .await?;

        Ok(std::time::Duration::MAX)
    }

    #[tracing::instrument(name = "fota", skip_all)]
    pub(super) async fn try_continue_fota(&mut self) -> std::time::Duration {
        if let Some(upload_state) = &mut self.upload_state {
            if let Some(towait) = upload_state
                .next_attempt
                .and_then(|i| i.checked_duration_since(std::time::Instant::now()))
            {
                return towait;
            } else {
                upload_state.next_attempt = None;
            }

            match self.upload_next_chunk().await {
                Ok(finished) => {
                    if finished {
                        // PANIC: If we're here we know it can't be `None`.
                        //        I currently don't see a better way to do this.
                        //        Please prove me wrong.
                        let upload_state = self.upload_state.take().unwrap();
                        let elapsed = upload_state.started.elapsed();
                        self.on_upload_finished(upload_state.kind, Ok(()), elapsed)
                            .await;
                    }
                }
                Err(e) => {
                    // PANIC: If we're here we know it can't be `None`.
                    let upload_state = self.upload_state.take().unwrap();
                    let elapsed = upload_state.started.elapsed();
                    self.on_upload_finished(upload_state.kind, Err(e), elapsed)
                        .await;
                }
            }

            // Our state changed so let our caller call us again immediately.
            // We don't want to loop here until the upload is done to allow
            // processing requests that arrived in the meantime.
            return std::time::Duration::ZERO;
        }

        // nothing to do
        std::time::Duration::MAX
    }

    /// Call this when you think the timezone has changed.
    ///
    /// It'll verify if that is actually the case and trigger updating the
    /// timezone on the device if needed.
    #[tokio_task_rpc(nowait)]
    pub fn handle_timezone_change(&self) -> Result<(), Error> {
        self.sleep_utctask.abort();
        Ok(())
    }

    /// Deletes this device if it's inactive.
    ///
    /// You probably want to call this repeatedly from a timer task. If it ends
    /// up getting deleted, the device task will not answer to any RPC requests
    /// anymore.
    #[tokio_task_rpc(nowait)]
    pub async fn delete_if_inactive(&mut self) -> Result<(), Error> {
        let now = tokio::time::Instant::now();
        if self.description.included || now < self.dont_delete_until {
            return Ok(());
        }

        self.forget("un-included device cleanup").await;
        Ok(())
    }

    pub async fn repair(&mut self) -> Result<(), Error> {
        tracing::info!(remote = true, "Start repair");

        let (value_descriptions, values) = self.fetch_values_and_descriptions().await?;

        value_descriptions
            .validate_values(&values)
            .context("failed to validate values")?;

        self.value_descriptions = value_descriptions;
        self.values = values;

        // A reboot or crash at this point could result in not loading this
        // device on the next start. We accept that race condition because the
        // repair is supposed to be triggered manually to fix incorrect or
        // inconsistent values and value descriptions.
        // There are some safeguards in the loading process like using
        // default-values for values with mismatching types, but there's still
        // a lot of cases where things can go wrong.
        self.save_value_descriptions()
            .await
            .context("can't save value descriptions")?;
        self.save_values().await.context("can't save values")?;

        tracing::info!(remote = true, "Repair succeeded");

        Ok(())
    }
}
